# Generated by Django 4.2.16 on 2026-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Class 1"),
                    ("2", "Class 2"),
                    ("3", "Class 3"),
                    ("4", "Class 4"),
                    ("5", "Class 5"),
                    ("6", "Class 6"),
                    ("7", "Class 7"),
                    ("8", "Class 8"),
                    ("9", "Class 9"),
                    ("10", "Class 10"),
                    ("11", "Class 11"),
                    ("12", "Class 12"),
                    ("bachelor", "Bachelor"),
                    ("master", "Master"),
                ],
                max_length=20,
            ),
        ),
    ]
